# rbenv exec bundle install --path vendor/bundle --binstubs .bundle/bin

source 'https://rubygems.org'

gem 'serverspec'
gem 'specinfra'
gem 'highline'
gem 'rake'

gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'busser'
gem 'busser-rspec'

gem 'itamae'
gem 'foodcritic'

